-- Run once after 0013, using the numbered migration ledger. No production deployment is automatic.
PRAGMA foreign_keys=ON;
ALTER TABLE studio_characters ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_characters_archive ON studio_characters(archived_at);
ALTER TABLE studio_world_records ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_world_records_archive ON studio_world_records(archived_at);
ALTER TABLE studio_story_projects ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_story_projects_archive ON studio_story_projects(archived_at);
ALTER TABLE studio_story_arcs ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_story_arcs_archive ON studio_story_arcs(archived_at);
ALTER TABLE studio_story_chapters ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_story_chapters_archive ON studio_story_chapters(archived_at);
ALTER TABLE studio_story_scenes ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_story_scenes_archive ON studio_story_scenes(archived_at);
ALTER TABLE studio_story_beats ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_story_beats_archive ON studio_story_beats(archived_at);
ALTER TABLE studio_character_journey ADD COLUMN archived_at TEXT;
ALTER TABLE studio_character_journey ADD COLUMN updated_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_character_journey_archive ON studio_character_journey(archived_at);
ALTER TABLE studio_media_assets ADD COLUMN archived_at TEXT;
CREATE INDEX IF NOT EXISTS idx_studio_media_assets_archive ON studio_media_assets(archived_at);
CREATE TABLE IF NOT EXISTS studio_pending_relationships(id TEXT PRIMARY KEY,source_type TEXT NOT NULL,source_id TEXT NOT NULL,target_name TEXT NOT NULL,target_type TEXT NOT NULL DEFAULT '',relation_label TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',resolved_target_type TEXT,resolved_target_id TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(source_type,source_id,target_name,target_type,relation_label));
CREATE TRIGGER IF NOT EXISTS stabilization_delete_character AFTER DELETE ON studio_characters BEGIN
DELETE FROM studio_favorites WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='character' AND source_id=OLD.id) OR (target_type='character' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='character' AND story_entity_id=OLD.id) OR (linked_entity_type='character' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='character' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='character' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='character' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='character' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_codex AFTER DELETE ON studio_world_records BEGIN
DELETE FROM studio_favorites WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='codex' AND source_id=OLD.id) OR (target_type='codex' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='codex' AND story_entity_id=OLD.id) OR (linked_entity_type='codex' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='codex' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='codex' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='codex' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='codex' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_location AFTER DELETE ON studio_world_locations BEGIN
DELETE FROM studio_favorites WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='location' AND source_id=OLD.id) OR (target_type='location' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='location' AND story_entity_id=OLD.id) OR (linked_entity_type='location' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='location' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='location' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='location' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='location' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_timeline AFTER DELETE ON studio_timeline_events BEGIN
DELETE FROM studio_favorites WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='timeline' AND source_id=OLD.id) OR (target_type='timeline' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='timeline' AND story_entity_id=OLD.id) OR (linked_entity_type='timeline' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='timeline' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='timeline' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='timeline' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='timeline' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_database AFTER DELETE ON studio_database_records BEGIN
DELETE FROM studio_favorites WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='database' AND source_id=OLD.id) OR (target_type='database' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='database' AND story_entity_id=OLD.id) OR (linked_entity_type='database' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='database' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='database' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='database' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='database' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_story_project AFTER DELETE ON studio_story_projects BEGIN
DELETE FROM studio_favorites WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='story_project' AND source_id=OLD.id) OR (target_type='story_project' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='story_project' AND story_entity_id=OLD.id) OR (linked_entity_type='story_project' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='story_project' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='story_project' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='story_project' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='story_project' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_story_arc AFTER DELETE ON studio_story_arcs BEGIN
DELETE FROM studio_favorites WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='story_arc' AND source_id=OLD.id) OR (target_type='story_arc' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='story_arc' AND story_entity_id=OLD.id) OR (linked_entity_type='story_arc' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='story_arc' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='story_arc' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='story_arc' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='story_arc' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_story_chapter AFTER DELETE ON studio_story_chapters BEGIN
DELETE FROM studio_favorites WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='story_chapter' AND source_id=OLD.id) OR (target_type='story_chapter' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='story_chapter' AND story_entity_id=OLD.id) OR (linked_entity_type='story_chapter' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='story_chapter' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='story_chapter' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='story_chapter' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='story_chapter' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_story_scene AFTER DELETE ON studio_story_scenes BEGIN
DELETE FROM studio_favorites WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='story_scene' AND source_id=OLD.id) OR (target_type='story_scene' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='story_scene' AND story_entity_id=OLD.id) OR (linked_entity_type='story_scene' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='story_scene' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='story_scene' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='story_scene' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='story_scene' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_story_beat AFTER DELETE ON studio_story_beats BEGIN
DELETE FROM studio_favorites WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='story_beat' AND source_id=OLD.id) OR (target_type='story_beat' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='story_beat' AND story_entity_id=OLD.id) OR (linked_entity_type='story_beat' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='story_beat' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='story_beat' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='story_beat' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='story_beat' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_journey AFTER DELETE ON studio_character_journey BEGIN
DELETE FROM studio_favorites WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='journey' AND source_id=OLD.id) OR (target_type='journey' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='journey' AND story_entity_id=OLD.id) OR (linked_entity_type='journey' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='journey' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='journey' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='journey' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='journey' AND entity_id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS stabilization_delete_media AFTER DELETE ON studio_media_assets BEGIN
DELETE FROM studio_favorites WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_collection_items WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_tag_assignments WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_media_attachments WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_review_comments WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_assignments WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_continuity_issues WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_universal_links WHERE (source_type='media' AND source_id=OLD.id) OR (target_type='media' AND target_id=OLD.id);
DELETE FROM studio_story_entity_links WHERE (story_entity_type='media' AND story_entity_id=OLD.id) OR (linked_entity_type='media' AND linked_entity_id=OLD.id);
DELETE FROM studio_pending_relationships WHERE source_type='media' AND source_id=OLD.id;
UPDATE studio_pending_relationships SET status='pending',resolved_target_type=NULL,resolved_target_id=NULL WHERE resolved_target_type='media' AND resolved_target_id=OLD.id;
DELETE FROM studio_import_results WHERE entity_type='media' AND entity_id=OLD.id;
DELETE FROM studio_entity_slugs WHERE entity_type='media' AND entity_id=OLD.id;
END;

-- Preserve field-aware import provenance on existing native record systems.
ALTER TABLE studio_world_locations ADD COLUMN import_metadata TEXT;
ALTER TABLE studio_timeline_events ADD COLUMN import_metadata TEXT;
ALTER TABLE studio_story_projects ADD COLUMN import_metadata TEXT;
ALTER TABLE studio_story_arcs ADD COLUMN import_metadata TEXT;
ALTER TABLE studio_story_chapters ADD COLUMN import_metadata TEXT;
ALTER TABLE studio_story_scenes ADD COLUMN import_metadata TEXT;
ALTER TABLE studio_story_beats ADD COLUMN import_metadata TEXT;
